POST http://localhost:3000/api/v1/probe/report
Content-Type: text/plain
#Content-Type: application/json

{
"v":"0.1", "k":"pewpew",
"f": {"https://github.githubassets.com/assets/frameworks-3d85abd8e6af4fc72b0afa253e125ef9.css": [".btn"]
}
}

###
